server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    config:
      enabled: false

  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5435/auth_db}
    username: ${AUTH_DB_USER:root}
    password: ${AUTH_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${AUTH_EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    # Forces the exact hostname so the Gateway inside Docker can find it
    hostname: host.docker.internal
    prefer-ip-address: false

jwt:
  secret: ${JWT_SECRET:ShopSphereSuperSecretKeyForJwtGenerationDoNotShare}